docs_dir: .

site_name: dtacs
repo_url: https://github.com/spaceml-org/DTACSNet
site_url: https://spaceml-org.github.io/DTACSNet
site_description: 🛰️ Cloud Detection and Atmospheric Correction With Efficient Deep Learning Models
site_author: Gonzalo Mateo-García
edit_uri: edit/main/docs/
repo_name: DTACSNet
use_directory_urls: false

# Configuration
theme:
  name: material
  language: en
  palette:
    - scheme: default
      primary: '#d49f0c'
      accent: '#d49f0c'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: '#201357'
      accent: white
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  # logo: assets/images/logo_ss2.png
  # favicon: assets/images/logo_ss2.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.indexes
    - header.autohide   


nav:
  - Home: 
    - README.md
  - Tutorials:
    - Inference Sentinel-2: tutorials/inference_Sentinel-2.ipynb
    - Inference Phi-Sat-II: tutorials/inference-Phi-Sat-II.ipynb

# Plugins
plugins:
  - search
  - same-dir
  - awesome-pages
  - mkdocstrings
  - mknotebooks:
      execute: false
      timeout: 100
      allow_errors: false

markdown_extensions:
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.pathconverter
  - pymdownx.tabbed
  - mdx_truly_sane_lists
  - pymdownx.tasklist

extra_css:
  - assets/style.css